language: cpp
dist: bionic
compiler: gcc

install: 
  - sudo apt update -qq
  # OCLint
  - sudo apt install libtinfo
  - ./install_oclint.sh

script: 
  - qmake
  - make
  - ./travis_qmake_gcc_cpp14_oclint
  # OCLint
  - ./do_oclint.sh
